- id: 329f52f35e7b47fab24c20e84400b6a4
  alias: Turn on lights in the morning
  trigger:
  - at: '7:00:00'
    platform: time
  condition: []
  action:
  - entity_id: scene.morning
    service: scene.turn_on
- id: 3217d9c8fbfcf5ca7ece38abec6830f4
  alias: Turn on lights during the day
  trigger:
    platform: time
    at: '11:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.day
- alias: Turn on evening lights
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 3.5
  condition:
    condition: time
    after: '12:00:00'
    before: '23:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.evening
- id: d304a677e39947d9b5e9f9ecc573a15c
  alias: Turn off lights at night
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.night
- alias: Turn off lights later at night
  trigger:
    platform: time
    at: '00:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.late_night
- id: ea98e4ef9ae6d93ba009ca22458d58b6
  alias: Front door left open
  trigger:
    platform: state
    entity_id: switch.front_door
    from: 'off'
    to: 'on'
    for:
      minutes: 5
  action:
  - service: notify.notify
    data:
      message: Front door has been left open
- id: 1db4e6aa504a4a18bc68ecd578bef958
  alias: Link living room window light
  trigger:
    platform: state
    entity_id:
    - switch.3wr_living_room_window_light
  action:
    service_template: '{% if trigger.to_state.state == "on" %} homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %} homeassistant.turn_off {% endif %}'
    entity_id:
    - switch.living_room_window_light
- id: 414b5dcc48c548d6bb69c3ff9145cf7a
  alias: Link office desk light
  trigger:
    platform: state
    entity_id:
    - switch.3wr_office_desk_light
    - switch.ws_office_desk_light
  action:
    service_template: '{% if trigger.to_state.state == "on" %} homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %} homeassistant.turn_off {% endif %}'
    entity_id:
    - switch.office_desk_light
- id: e1ccd95f74cd438595e6b566b3d29290
  alias: Link office games shelf light
  trigger:
    platform: state
    entity_id:
    - switch.3wr_office_games_shelf_light
    - switch.ws_office_games_shelf_light
  action:
    service_template: '{% if trigger.to_state.state == "on" %} homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %} homeassistant.turn_off {% endif %}'
    entity_id:
    - switch.office_games_shelf_light
- id: 4a05b64acd6541b48c4b76eed163f886
  alias: Link office window light
  trigger:
    platform: state
    entity_id:
    - switch.3wr_office_window_light
  action:
    service_template: '{% if trigger.to_state.state == "on" %} homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %} homeassistant.turn_off {% endif %}'
    entity_id:
    - switch.office_window_light
- id: 09bbe8f9050043b2919b2f213de9ad36
  alias: Link bedroom window light
  trigger:
    platform: state
    entity_id:
    - switch.3wr_bedroom_window_light
  action:
    service_template: '{% if trigger.to_state.state == "on" %} homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %} homeassistant.turn_off {% endif %}'
    entity_id:
    - switch.bedroom_window_light
- id: '1546800010347'
  alias: Certificate expiry
  trigger:
  - below: '14'
    entity_id: sensor.ssl_certificate_expiry
    platform: numeric_state
  condition: []
  action:
  - data:
      message: TLS certificate about to expire
      notification_id: cert
      title: Certificate expiration
    service: persistent_notification.create
- id: '1553203358695'
  alias: Wake up
  trigger:
  - at: '09:30:00'
    platform: time
  condition: []
  action:
  - alias: ''
    data:
      brightness: 1
      entity_id: light.wardrobe
    service: light.turn_on
  - data:
      brightness: 64
      entity_id: light.wardrobe
      transition: 60
    service: light.turn_on
